Import the dependencies

In [1]:
import pandas as pd
import numpy as np

In [2]:
#! pip install openpyxl

In [2]:
# Reading the main file
dati_bes = pd.read_excel('E:\Geospatial_Project\Dati Bes\Bes\Indicatori_per_provincia_sesso.xlsx')

In [3]:
dati_bes

,DOMINIO,CODICE,INDICATORE,SESSO,TERRITORIO,UNITA_MISURA,FONTE,V_2004,V_2005,V_2006,...,V_2011,V_2012,V_2013,V_2014,V_2015,V_2016,V_2017,V_2018,V_2019,NOTE
0,Salute,01SAL001,Speranza di vita alla nascita,Maschi,Piemonte,numero medio di anni,Istat - Tavole di mortalità della popolazione ...,77.6,77.9,78.1,...,79.4,79.6,79.7,80.2,79.9,80.4,80.4,80.5,NaN,NaN
1,Salute,01SAL001,Speranza di vita alla nascita,Maschi,Torino,numero medio di anni,Istat - Tavole di mortalità della popolazione ...,78.1,78.2,78.6,...,79.7,80,80,80.7,80.3,80.9,80.9,80.9,NaN,NaN
2,Salute,01SAL001,Speranza di vita alla nascita,Maschi,Vercelli,numero medio di anni,Istat - Tavole di mortalità della popolazione ...,76.2,76.7,76.8,...,78.7,79.2,78.7,78.9,78.8,79.4,78.9,80,NaN,NaN
3,Salute,01SAL001,Speranza di vita alla nascita,Maschi,Novara,numero medio di anni,Istat - Tavole di mortalità della popolazione ...,77.5,78.1,78.3,...,79.5,79.9,79.6,80.4,80.1,80.5,80.9,80.5,NaN,NaN
4,Salute,01SAL001,Speranza di vita alla nascita,Maschi,Cuneo,numero medio di anni,Istat - Tavole di mortalità della popolazione ...,77.7,77.8,77.9,...,79.4,79.5,79.7,79.9,79.7,80.4,80.2,80.4,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11441,Qualità dei servizi,12SER001P,Emigrazione ospedaliera in altra regione,Totale,Sud Sardegna,valori percentuali,Istat - Elaborazione su dati Ministero della S...,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,....,....,NaN,NaN
11442,Qualità dei servizi,12SER001P,Emigrazione ospedaliera in altra regione,Totale,Nord,valori percentuali,Istat - Elaborazione su dati Ministero della S...,5,4.9,4.9,...,4.6,4.4,4.4,4.3,4.4,5.2,4.4,4.4,NaN,NaN
11443,Qualità dei servizi,12SER001P,Emigrazione ospedaliera in altra regione,Totale,Centro,valori percentuali,Istat - Elaborazione su dati Ministero della S...,5.7,5.5,5.6,...,5.8,5.8,5.9,6.1,6.3,6.8,6.5,6.4,NaN,NaN
11444,Qualità dei servizi,12SER001P,Emigrazione ospedaliera in altra regione,Totale,Mezzogiorno,valori percentuali,Istat - Elaborazione su dati Ministero della S...,9.8,9.7,9.5,...,9.4,9.4,9.2,9.2,9.3,9.9,9.4,9.6,NaN,NaN
11445,Qualità dei servizi,12SER001P,Emigrazione ospedaliera in altra regione,Totale,Italia,valori percentuali,Istat - Elaborazione su dati Ministero della S...,6.8,6.7,6.6,...,6.5,6.4,6.3,6.3,6.4,7.1,6.5,6.5,NaN,NaN

In [4]:
dati_bes.isnull()

,DOMINIO,CODICE,INDICATORE,SESSO,TERRITORIO,UNITA_MISURA,FONTE,V_2004,V_2005,V_2006,...,V_2011,V_2012,V_2013,V_2014,V_2015,V_2016,V_2017,V_2018,V_2019,NOTE
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,True
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,True
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,True
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,True
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11441,False,False,False,False,False,False,False,True,True,True,...,True,True,True,True,True,True,False,False,True,True
11442,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,True
11443,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,True
11444,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,True
11445,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,True

In [5]:
len(dati_bes)

11446

In [6]:
dati_bes.columns

Index(['DOMINIO', 'CODICE', 'INDICATORE', 'SESSO', 'TERRITORIO',
       'UNITA_MISURA', 'FONTE', 'V_2004', 'V_2005', 'V_2006', 'V_2007',
       'V_2008', 'V_2009', 'V_2010', 'V_2011', 'V_2012', 'V_2013', 'V_2014',
       'V_2015', 'V_2016', 'V_2017', 'V_2018', 'V_2019', 'NOTE'],
      dtype='object')

In [7]:
header = dati_bes.columns

In [10]:
tabella_new = pd.DataFrame(columns=header)
tabella_new

Empty DataFrame
Columns: [DOMINIO, CODICE, INDICATORE, SESSO, TERRITORIO, UNITA_MISURA, FONTE, V_2004, V_2005, V_2006, V_2007, V_2008, V_2009, V_2010, V_2011, V_2012, V_2013, V_2014, V_2015, V_2016, V_2017, V_2018, V_2019, NOTE]
Index: []

[0 rows x 24 columns]

In [11]:
# The pattern that change 
for j in range(len(dati_bes)):
    mini_ds = dati_bes.iloc[j]
    tabella_new = tabella_new.append(mini_ds)
    if mini_ds['TERRITORIO'] == 'Italia':
        Dominio = dati_bes.iloc[j]['DOMINIO']
        Indicatore = dati_bes.iloc[j]['INDICATORE']
        Sesso = dati_bes.iloc[j]['SESSO']
        Unita = dati_bes.iloc[j]['UNITA_MISURA']
        tabella_new.to_excel('E:/Geospatial_Project/Nuovi_Dati2/{Dominio}-{Indicatore}-{Sesso}-{Unita}.xlsx'.format(Dominio=Dominio, Indicatore=Indicatore, Sesso = Sesso, Unita = Unita))
        tabella_new = pd.DataFrame(columns=header)

In [12]:
import os

In [13]:
files_ = os.listdir(path='Nuovi_Dati2')
files_

['Ambiente-Conferimento dei rifiuti urbani in discarica-Totale-valori percentuali.xlsx',
 'Ambiente-Dispersione da rete idrica comunale-Totale-valori percentuali.xlsx',
 'Ambiente-Disponibilità di verde urbano-Totale-m2 per abitante.xlsx',
 'Ambiente-Energia elettrica da fonti rinnovabili-Totale-valori percentuali.xlsx',
 'Ambiente-Impermeabilizzazione del suolo da copertura artificiale-Totale-valori percentuali.xlsx',
 "Ambiente-Qualità dell'aria urbana - Biossido di azoto-Totale-valori percentuali.xlsx",
 "Ambiente-Qualità dell'aria urbana - PM10-Totale-valori percentuali.xlsx",
 'Ambiente-Raccolta differenziata dei rifiuti urbani-Totale-valori percentuali.xlsx',
 'Benessere economico-Importo medio annuo pro-capite dei redditi pensionistici-Femmine-euro.xlsx',
 'Benessere economico-Importo medio annuo pro-capite dei redditi pensionistici-Maschi-euro.xlsx',
 'Benessere economico-Importo medio annuo pro-capite dei redditi pensionistici-Totale-euro.xlsx',
 'Benessere economico-Patrimonio pro capite-Totale-euro.xlsx',
 'Benessere economico-Pensionati con pensione di basso importo-Femmine-valori percentuali.xlsx',
 'Benessere economico-Pensionati con pensione di basso importo-Maschi-valori percentuali.xlsx',
 'Benessere economico-Pensionati con pensione di basso importo-Totale-valori percentuali.xlsx',
 'Benessere economico-Reddito medio disponibile pro capite-Totale-euro.xlsx',
 'Benessere economico-Retribuzione media annua dei lavoratori dipendenti-Femmine-euro.xlsx',
 'Benessere economico-Retribuzione media annua dei lavoratori dipendenti-Maschi-euro.xlsx',
 'Benessere economico-Retribuzione media annua dei lavoratori dipendenti-Totale-euro.xlsx',
 'Benessere economico-Tasso di ingresso in sofferenza dei prestiti bancari alle famiglie-Totale-valori percentuali.xlsx',
 'Innovazione, ricerca e creatività-Addetti nelle imprese culturali-Totale-valori percentuali.xlsx',
 'Innovazione, ricerca e creatività-Mobilità dei laureati italiani (25-39 anni)-Totale-per 1.000 laureati residenti.xlsx',
 'Innovazione, ricerca e creatività-Propensione alla brevettazione-Totale-per milioni di abitanti.xlsx',
 'Istruzione e formazione-Competenza alfabetica non adeguata-Femmine-valori percentuali.xlsx',
 'Istruzione e formazione-Competenza alfabetica non adeguata-Maschi-valori percentuali.xlsx',
 'Istruzione e formazione-Competenza alfabetica non adeguata-Totale-valori percentuali.xlsx',
 'Istruzione e formazione-Competenza numerica non adeguata-Femmine-valori percentuali.xlsx',
 'Istruzione e formazione-Competenza numerica non adeguata-Maschi-valori percentuali.xlsx',
 'Istruzione e formazione-Competenza numerica non adeguata-Totale-valori percentuali.xlsx',
 'Istruzione e formazione-Giovani che non lavorano e non studiano (Neet)-Totale-valori percentuali.xlsx',
 'Istruzione e formazione-Laureati e altri titoli terziari (25-39 anni)-Totale-valori percentuali.xlsx',
 'Istruzione e formazione-Partecipazione alla formazione continua-Totale-valori percentuali.xlsx',
 "Istruzione e formazione-Passaggio all'università-Totale-valori percentuali (tasso specifico di coorte).xlsx",
 'Istruzione e formazione-Persone con almeno il diploma (25-64 anni)-Totale-valori percentuali.xlsx',
 "Lavoro e conciliazione dei tempi di vita-Giornate retribuite nell'anno (lavoratori dipendenti)-Femmine-valori percentuali.xlsx",
 "Lavoro e conciliazione dei tempi di vita-Giornate retribuite nell'anno (lavoratori dipendenti)-Maschi-valori percentuali.xlsx",
 "Lavoro e conciliazione dei tempi di vita-Giornate retribuite nell'anno (lavoratori dipendenti)-Totale-valori percentuali.xlsx",
 'Lavoro e conciliazione dei tempi di vita-Tasso di infortuni mortali e inabilità permanente-Femmine-per 10.000 occupati.xlsx',
 'Lavoro e conciliazione dei tempi di vita-Tasso di infortuni mortali e inabilità permanente-Maschi-per 10.000 occupati.xlsx',
 'Lavoro e conciliazione dei tempi di vita-Tasso di infortuni mortali e inabilità permanente-Totale-per 10.000 occupati.xlsx',
 'Lavoro e conciliazione dei tempi di vita-Tasso di mancata partecipazione al lavoro giovanile (15-29 anni)-Femmine-valori percentuali.xlsx',
 'Lavoro e conciliazione dei tempi di vita-Tasso di mancata partecipazione al lavoro giovanile (15-29 anni)-Maschi-valori percentuali.xlsx',
 'Lavoro e conciliazione dei tempi di vita-Tasso di mancata partecipazione al lavoro giovanile (15-29 anni)-Totale-valori percentuali.xlsx',
 'Lavoro e conciliazione dei tempi di vita-Tasso di mancata partecipazione al lavoro-Femmine-valori percentuali.xlsx',
 'Lavoro e conciliazione dei tempi di vita-Tasso di mancata partecipazione al lavoro-Maschi-valori percentuali.xlsx',
 'Lavoro e conciliazione dei tempi di vita-Tasso di mancata partecipazione al lavoro-Totale-valori percentuali.xlsx',
 'Lavoro e conciliazione dei tempi di vita-Tasso di occupazione (20-64 anni)-Femmine-valori percentuali.xlsx',
 'Lavoro e conciliazione dei tempi di vita-Tasso di occupazione (20-64 anni)-Maschi-valori percentuali.xlsx',
 'Lavoro e conciliazione dei tempi di vita-Tasso di occupazione (20-64 anni)-Totale-valori percentuali.xlsx',
 'Lavoro e conciliazione dei tempi di vita-Tasso di occupazione giovanile (15-29 anni)-Femmine-valori percentuali.xlsx',
 'Lavoro e conciliazione dei tempi di vita-Tasso di occupazione giovanile (15-29 anni)-Maschi-valori percentuali.xlsx',
 'Lavoro e conciliazione dei tempi di vita-Tasso di occupazione giovanile (15-29 anni)-Totale-valori percentuali.xlsx',
 'Paesaggio e patrimonio culturale-Densità di verde storico-Totale-per 100 m2.xlsx',
 'Paesaggio e patrimonio culturale-Densità e rilevanza del patrimonio museale-Totale-per 100 km2.xlsx',
 'Paesaggio e patrimonio culturale-Diffusione delle aziende agrituristiche-Totale-per 100 km2.xlsx',
 'Politica e istituzioni-Affollamento degli istituti di pena-Totale-valori percentuali.xlsx',
 'Politica e istituzioni-Amministratori comunali con meno di 40 anni-Totale-valori percentuali.xlsx',
 'Politica e istituzioni-Amministratori comunali donne-Totale-valori percentuali.xlsx',
 'Politica e istituzioni-Amministrazioni provinciali',
 'Politica e istituzioni-Comuni',
 'Politica e istituzioni-Partecipazione elettorale (elezioni regionali)-Totale-valori percentuali.xlsx',
 'Politica e istituzioni-Partecipazione elettorale-Totale-valori percentuali.xlsx',
 "Qualità dei servizi-Bambini che hanno usufruito dei servizi comunali per l'infanzia-Totale-valori percentuali.xlsx",
 'Qualità dei servizi-Emigrazione ospedaliera in altra regione-Totale-valori percentuali.xlsx',
 'Qualità dei servizi-Irregolarità del servizio elettrico-Totale-numero medio per utente.xlsx',
 'Qualità dei servizi-Posti-km offerti dal Tpl-Totale-valori per abitante.xlsx',
 'Relazioni sociali-Organizzazioni non profit-Totale-per 10.000 abitanti.xlsx',
 'Relazioni sociali-Scuole accessibili-Totale-valori percentuali.xlsx',
 'Salute-Mortalità infantile-Totale-per 1.000 nati vivi.xlsx',
 'Salute-Mortalità per demenze e malattie del sistema nervoso (65 anni e più)-Femmine-tassi standardizzati per 10.000 residenti.xlsx',
 'Salute-Mortalità per demenze e malattie del sistema nervoso (65 anni e più)-Maschi-tassi standardizzati per 10.000 residenti.xlsx',
 'Salute-Mortalità per demenze e malattie del sistema nervoso (65 anni e più)-Totale-tassi standardizzati per 10.000 residenti.xlsx',
 'Salute-Mortalità per incidenti stradali (15-34 anni)-Femmine-tassi standardizzati per 10.000 residenti.xlsx',
 'Salute-Mortalità per incidenti stradali (15-34 anni)-Maschi-tassi standardizzati per 10.000 residenti.xlsx',
 'Salute-Mortalità per incidenti stradali (15-34 anni)-Totale-tassi standardizzati per 10.000 residenti.xlsx',
 'Salute-Mortalità per tumore (20-64 anni)-Femmine-tassi standardizzati per 10.000 residenti.xlsx',
 'Salute-Mortalità per tumore (20-64 anni)-Maschi-tassi standardizzati per 10.000 residenti.xlsx',
 'Salute-Mortalità per tumore (20-64 anni)-Totale-tassi standardizzati per 10.000 residenti.xlsx',
 'Salute-Speranza di vita alla nascita-Femmine-numero medio di anni.xlsx',
 'Salute-Speranza di vita alla nascita-Maschi-numero medio di anni.xlsx',
 'Salute-Speranza di vita alla nascita-Totale-numero medio di anni.xlsx',
 'Sicurezza-Altri delitti violenti denunciati-Totale-per 10.000 abitanti.xlsx',
 'Sicurezza-Delitti diffusi denunciati-Totale-per 10.000 abitanti.xlsx',
 'Sicurezza-Mortalità stradale in ambito extraurbano-Totale-valori percentuali.xlsx',
 'Sicurezza-Omicidi-Totale-per 100.000 abitanti.xlsx']

In [27]:
# controllo che la lunghezza dei file sia sempre la stessa
to_chekc = []
for file in files_:
    if file.endswith('.xlsx'):
        excel_ = pd.read_excel('Nuovi_Dati2/'+file)
        if len(excel_) != 135:
            print(file + str(len(excel_)))
            to_chekc.append(file)

Ambiente-Dispersione da rete idrica comunale-Totale-valori percentuali.xlsx134
Istruzione e formazione-Competenza alfabetica non adeguata-Femmine-valori percentuali.xlsx131
Istruzione e formazione-Competenza alfabetica non adeguata-Maschi-valori percentuali.xlsx131
Istruzione e formazione-Competenza alfabetica non adeguata-Totale-valori percentuali.xlsx131
Istruzione e formazione-Competenza numerica non adeguata-Femmine-valori percentuali.xlsx131
Istruzione e formazione-Competenza numerica non adeguata-Maschi-valori percentuali.xlsx131
Istruzione e formazione-Competenza numerica non adeguata-Totale-valori percentuali.xlsx131
Relazioni sociali-Scuole accessibili-Totale-valori percentuali.xlsx131

Come possiamo vedere vi sono alcuni files con una lunghezza leggermente diversa rispetto ad altri. 
<br>
Cerchiamo di capire se queste differenze sono sistematiche e quindi dovute :
* ad una mancanza della provincia di mandare i dati;
* al fatto che la provincia in questione non esistesse al momento della rilevazione iniziale;
* altri motivi al momento ignoti

In [25]:
df_prova = pd.read_excel('Nuovi_Dati2/Benessere economico-Retribuzione media annua dei lavoratori dipendenti-Totale-euro.xlsx')
s2 = df_prova.TERRITORIO.unique().tolist()
path = 'Nuovi_Dati2/'
Territori_Mancanti = {}
for f in to_chekc:
    df_check = pd.read_excel(path + f)
    s1 =df_check.TERRITORIO.unique().tolist()
    mis_val = set(s2) - set(s1) 
    Territori_Mancanti[f] = mis_val

In [26]:
Territori_Mancanti

{'Ambiente-Dispersione da rete idrica comunale-Totale-valori percentuali.xlsx': {'Sud Sardegna'},
 'Istruzione e formazione-Competenza alfabetica non adeguata-Femmine-valori percentuali.xlsx': {'Carbonia-Iglesias',
  'Medio Campidano',
  'Ogliastra',
  'Olbia-Tempio'},
 'Istruzione e formazione-Competenza alfabetica non adeguata-Maschi-valori percentuali.xlsx': {'Carbonia-Iglesias',
  'Medio Campidano',
  'Ogliastra',
  'Olbia-Tempio'},
 'Istruzione e formazione-Competenza alfabetica non adeguata-Totale-valori percentuali.xlsx': {'Carbonia-Iglesias',
  'Medio Campidano',
  'Ogliastra',
  'Olbia-Tempio'},
 'Istruzione e formazione-Competenza numerica non adeguata-Femmine-valori percentuali.xlsx': {'Carbonia-Iglesias',
  'Medio Campidano',
  'Ogliastra',
  'Olbia-Tempio'},
 'Istruzione e formazione-Competenza numerica non adeguata-Maschi-valori percentuali.xlsx': {'Carbonia-Iglesias',
  'Medio Campidano',
  'Ogliastra',
  'Olbia-Tempio'},
 'Istruzione e formazione-Competenza numerica non adeguata-Totale-valori percentuali.xlsx': {'Carbonia-Iglesias',
  'Medio Campidano',
  'Ogliastra',
  'Olbia-Tempio'},
 'Relazioni sociali-Scuole accessibili-Totale-valori percentuali.xlsx': {'Carbonia-Iglesias',
  'Medio Campidano',
  'Ogliastra',
  'Olbia-Tempio'}}

Fortunatamente possiamo notare come tutte le provincie mancanti appartengano alla regione Sardegna. Per tanto possiamo ipotizzare che ciò sia dovuto ad una motivazione territoriale come ad esempio una mancanza di tecnologie e/o personale per monitorare le misure in questione.